/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment4;

/**
 *
 * @author shnag4707
 */
public class A4Q9 extends javax.swing.JFrame {

    /**
     * Creates new form A4Q9
     */
    public A4Q9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstNumField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SecondNumField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addingBut = new javax.swing.JButton();
        subtractingBut = new javax.swing.JButton();
        multiplyingBut = new javax.swing.JButton();
        dividingBut = new javax.swing.JButton();
        resultBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FirstNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNumFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("First Number:");

        SecondNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondNumFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Second Number:");

        addingBut.setText("+");
        addingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addingButActionPerformed(evt);
            }
        });

        subtractingBut.setText("-");
        subtractingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractingButActionPerformed(evt);
            }
        });

        multiplyingBut.setText("*");
        multiplyingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyingButActionPerformed(evt);
            }
        });

        dividingBut.setText("%");
        dividingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividingButActionPerformed(evt);
            }
        });

        jLabel3.setText("The Result is :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(resultBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addingBut)
                                .addGap(47, 47, 47)
                                .addComponent(subtractingBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(multiplyingBut)
                                .addGap(43, 43, 43)
                                .addComponent(dividingBut))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SecondNumField)
                                    .addComponent(FirstNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecondNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addingBut)
                    .addComponent(subtractingBut)
                    .addComponent(multiplyingBut)
                    .addComponent(dividingBut))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNumFieldActionPerformed
        
    }//GEN-LAST:event_FirstNumFieldActionPerformed

    private void addingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addingButActionPerformed
        // get the number from first field
        String firstNumString = FirstNumField.getText();
        
        //convert the text into integer
        int firstNum = Integer.parseInt(firstNumString);
        
        // get the number from first field
        String secondNumString = SecondNumField.getText();
        
        //convert the text into integer
        int secondNum = Integer.parseInt(secondNumString);
        
        //add the two numbers together
        int result = firstNum + secondNum;
        
        //display result into the result box
        resultBox.setText("" + result);
    }//GEN-LAST:event_addingButActionPerformed

    private void SecondNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondNumFieldActionPerformed
        
    }//GEN-LAST:event_SecondNumFieldActionPerformed

    private void subtractingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractingButActionPerformed
        // get the number from first field
        String firstNumString = FirstNumField.getText();
        
        //convert the text into integer
        int firstNum = Integer.parseInt(firstNumString);
        
        // get the number from first field
        String secondNumString = SecondNumField.getText();
        
        //convert the text into integer
        int secondNum = Integer.parseInt(secondNumString);
        
        //subtract the two numbers
        int result = firstNum - secondNum;
        
        //display result into the result box
        resultBox.setText(""+ result);
    }//GEN-LAST:event_subtractingButActionPerformed

    private void multiplyingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyingButActionPerformed
        // get the number from first field
        String firstNumString = FirstNumField.getText();
        
        //convert the text into integer
        int firstNum = Integer.parseInt(firstNumString);
        
        // get the number from first field
        String secondNumString = SecondNumField.getText();
        
        //convert the text into integer
        int secondNum = Integer.parseInt(secondNumString);
        
        //multiply the two numbers together
        int result = firstNum*secondNum;
        
        //display result in the result box
        resultBox.setText(""+ result);
    }//GEN-LAST:event_multiplyingButActionPerformed

    private void dividingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividingButActionPerformed
        // get the number from first field
        String firstNumString = FirstNumField.getText();
        
        //convert the text into integer
        int firstNum = Integer.parseInt(firstNumString);
        
        // get the number from first field
        String secondNumString = SecondNumField.getText();
        
        //convert the text into integer
        int secondNum = Integer.parseInt(secondNumString);
        
        //divide first number by second number
        int result = firstNum/secondNum;
        
        //displaay the result in text box
        resultBox.setText(""+ result);
    }//GEN-LAST:event_dividingButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A4Q9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A4Q9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A4Q9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A4Q9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A4Q9().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstNumField;
    private javax.swing.JTextField SecondNumField;
    private javax.swing.JButton addingBut;
    private javax.swing.JButton dividingBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton multiplyingBut;
    private javax.swing.JTextField resultBox;
    private javax.swing.JButton subtractingBut;
    // End of variables declaration//GEN-END:variables
}
