/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment4;

/**
 *
 * @author shnag4707
 */
public class A4Q_10 extends javax.swing.JFrame {

    /**
     * Creates new form A4Q_10
     */
    public A4Q_10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FerText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CelText = new javax.swing.JTextField();
        FerToCelBut = new javax.swing.JButton();
        CelToFerBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        jLabel1.setText("Degrees Fahrenheit:");

        jLabel2.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        jLabel2.setText("Degrees Celsius:");

        CelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelTextActionPerformed(evt);
            }
        });

        FerToCelBut.setText("F --> C");
        FerToCelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FerToCelButActionPerformed(evt);
            }
        });

        CelToFerBut.setText("C --> F");
        CelToFerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelToFerButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(CelText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FerText, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FerToCelBut)
                    .addComponent(CelToFerBut))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FerText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FerToCelBut))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CelText, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CelToFerBut))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelTextActionPerformed

    private void FerToCelButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FerToCelButActionPerformed
        // get the temp' in F' in textbox
        String ferString = FerText.getText();
        
        //convert the degrees F to an integer
        double ferInt = Double.parseDouble(ferString);
        
        //calculate the degrees in Celcius in 3 steps for more accurate answer
        double devideBy = 9/5.0;
        double celCalc = ferInt - 32;
        double celInt = celCalc/devideBy;
        
        //round the number to 4 decimal places
        double celR = celInt*10000.0;
        celR = Math.round(celR);
        double celNum = celR/10000.0; 
        
        //display the answer in the c' textbox
        CelText.setText(" " + celNum);
    }//GEN-LAST:event_FerToCelButActionPerformed

    private void CelToFerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelToFerButActionPerformed
        // get the temp' in C' in textbox
        String celstring = CelText.getText();
        
        //convert the degrees in C' to an integer
        double celInt = Double.parseDouble(celstring);
        
        //calculate the degrees in F' in 3 steps for more accurate answer
        double multiplyBy = 9/5.0;
        double ferCalc = (celInt*multiplyBy);
        double ferInt = ferCalc + 32;
        
        //round the number to 4 decimal places
        double ferR = ferInt*10000.0;
        ferR = Math.round(ferR);
        double ferNum = ferR/10000.0; 
        
        //display the answer in the f' textbox
        FerText.setText(" "+ ferNum);
    }//GEN-LAST:event_CelToFerButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A4Q_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A4Q_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A4Q_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A4Q_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A4Q_10().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CelText;
    private javax.swing.JButton CelToFerBut;
    private javax.swing.JTextField FerText;
    private javax.swing.JButton FerToCelBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
